# params.yaml
env:
  env_id: PickCube-v0
  obs_mode: state
  control_mode: pd_joint_delta_pos
  render_mode: cameras

prepare:
  window_size: 4
  load_count: -1
  transformations: []
  raw_data_path: data/raw/PickCube/
  prepared_graph_data_path: data/prepared/graph/PickCube/
  prepared_mlp_data_path: data/prepared/mlp/PickCube/
  data_file: trajectory.state.pd_joint_delta_pos.h5
train:
  obs_mode: state
  control_mode: pd_joint_delta_pos
  render_mode: cameras
  batch_size: 64
  num_workers: 4
  lr: 0.001
  seed: 42
  log_dir: logs/output
  plot_dir: logs/output/plots
  env_id: PickCube-v0
  iterations: 30000
  eval: false
  model: GAT
  model_params:
    num_heads: 2
    hidden_dim: 256
    dropout: 0.5


evaluate:
  render: true
  render_mode: human
