# params.yaml
env_id: PickCube-v0
obs_mode: state
control_mode: pd_joint_delta_pos
render_mode: cameras
raw_data_path: data/raw/PickCube/
prepared_data_path: data/prepared/PickCube/
data_file: trajectory.state.pd_joint_delta_pos.h5

prepare:
  load_count: -1
  transformations: []

train:
  obs_mode: state
  control_mode: pd_joint_delta_pos
  render_mode: cameras
  num_steps: 100000
  batch_size: 128
  num_workers: 4
  lr: 0.001
  seed: 42
  log_dir: logs/output
  env_id: PickCube-v0
  iterations: 30000
  eval: false
  model: GAT
  model_params:
    num_heads: 4
    hidden_dim: 256
    dropout: 0.1
    

evaluate:
  render: True
  render_mode: human