wandb_version: 1

train.batch_size:
  value: 128
train.lr:
  value: 0.0001
train.model_params.dropout:
  value: 0.7
train.model_params.hidden_dim:
  value: 32
train.model_params.num_heads:
  value: 8
