wandb_version: 1

train.batch_size:
  value: 256
train.lr:
  value: 0.001
train.model_params.dropout:
  value: 0.25
train.model_params.hidden_dim:
  value: 512
train.model_params.num_heads:
  value: 8
